# Generated by Django 5.0.3 on 2024-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0002_educationalresource_plasticcollectionschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
    ]
