# Generated by Django 5.0.3 on 2024-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0003_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approve',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
    ]
