# Generated by Django 5.0.3 on 2024-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0004_customer_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='educational_resources/'),
        ),
    ]
