# Generated by Django 5.0.3 on 2024-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0006_plasticcollection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasticcollection',
            name='user',
        ),
        migrations.AddField(
            model_name='plasticcollection',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
