# Generated by Django 5.0.3 on 2024-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0007_remove_plasticcollection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticcollection',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
