# Generated by Django 5.0.3 on 2024-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0008_alter_plasticcollection_amount_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticcollectionschedule',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plasticcollectionschedule',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plasticcollectionschedule',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
