# Generated by Django 5.0.3 on 2024-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0009_plasticcollectionschedule_amount_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticcollection',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
