# Generated by Django 5.0.3 on 2024-03-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0010_alter_plasticcollection_amount_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
