# Generated by Django 5.0.3 on 2024-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0011_plasticcollection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasticcollection',
            name='user',
        ),
        migrations.AddField(
            model_name='plasticcollection',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
