# Generated by Django 5.0.3 on 2024-03-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0014_remove_payment_amount_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
