# Generated by Django 5.0.3 on 2024-03-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0016_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
