# Generated by Django 5.0.3 on 2024-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0017_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticcollection',
            name='plastic_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
