# Generated by Django 5.0.3 on 2024-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0018_plasticcollection_plastic_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
