# Generated by Django 5.0.3 on 2024-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0019_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='house_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
