# Generated by Django 5.0.3 on 2024-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0020_customer_house_number_customer_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
