# Generated by Django 5.0.3 on 2024-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smApp', '0022_plasticcollectionschedule_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticcollectionschedule',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
